### ISSUE TITLE
Add lock cell status and button for ZTE MF28X series

### ISSUE THREAD

**Issue by stich86** [4IceG/luci-app-3ginfo-lite#13]
Hi @4IceG,

Do you think it's possible to add two feature like these:

- display current cell lock (using AT+ZLOCKCELL? command)
- ability to lock current cell displayed (also on additional band) using a button (still using AT+ZLOCKCELL=earnfc,pci)

If I can help you in any way let me know 

Thx

**Comment by 4IceG** [comment]
Hi @stich86 
In general, I thought to add this option to 3ginfo as a new tab, only I saw it so that the current bands from aggregation are downloaded to the table and in the table there are buttons only buttons responsible for blocking the band. This is to be done if you know Luci JS better, I stopped in the code at some point and left the topic for later.
