### ISSUE TITLE
luasrc?

### ISSUE THREAD

**Issue by kyliezero** [4IceG/luci-app-3ginfo-lite#4]
I was wondering, why does this package not appear in the LuCi menu, it turns out that there is no "luasrc" file from this package, do you really not need it?

**Comment by 4IceG** [comment]
Hi, the package is written for the current Luci JS so there won't be any
"luasrc" files there because the package doesn't need them. Log out, clear
browser cache or restart the router to refresh the cache. Everything should
work if Openwrt is up to date and the dependencies are satisfied.

śr., 29 gru 2021, 22:58 użytkownik kyliezero ***@***.***>
napisał:

**Comment by kyliezero** [comment]
here I use lede, are there other dependants that need to be installed, so that it can work smoothly..

**Comment by 4IceG** [comment]
Lede is an old system already, I don't know what modem you have, but maybe
it will be supported by the usual 3ginfo package along with the Luci
package.

czw., 30 gru 2021, 00:46 użytkownik kyliezero ***@***.***>
napisał:
